# Generated by Django 5.2.2 on 2025-06-05 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_dataentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='data_value',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='title',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='area',
            field=models.CharField(choices=[('HQ', 'HQ'), ('RI', 'RI')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='eis_neis_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='email_id',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='mac_id_of_system',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='name_of_employee',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='official_mobile_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='reason_for_registration',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
